# Version-table script for the CORD-instrumented copy (no .git in the copy).
#
# cFE uses this file instead of its git script when it exists in the mission defs
# directory: cfe/cmake/mission_build.cmake L130-137 ("If this script exists in the
# mission defs directory (user-supplied) then use that"). It installs the version
# table generated by the ENV build (cfs_ref/cFS/build-native_std/src/
# cfe_module_version_table.c, sha256 4615470b...) byte for byte, so the instrumented
# build reports the same module versions as the ENV build. Output path and
# configure_file() use are as in cfe/cmake/generate_git_module_version.cmake L76-79.
configure_file(${CMAKE_CURRENT_LIST_DIR}/env_module_version_table.c ${BIN}/src/cfe_module_version_table.c COPYONLY)
